<?php

$url = 'https://trade.jd.com/shopping/dynamic/payAndShip/getAdditShipment.action';
$params = [
    'paymentId' => 4, //在线支付
    'shipParam.reset311' => 0,
    'resetFlag' => 1000000000,
    'shipParam.onlinePayType' => 0,//在线支付
    'typeFlag' => 0,//初始化京准达波次时效的参数
    'promiseTagType' => ''//京准达
];

$str = 'overseaPurchaseCookies:
vendorRemarks: [{"venderId":"676426","remark":""}]
submitOrderParam.sopNotPutInvoice: true
submitOrderParam.trackID: TestTrackId
submitOrderParam.ignorePriceChange: 0
submitOrderParam.btSupport: 0
submitOrderParam.eid: QOYNBYX6GPAIXNDND36C6VATHCPYGCWPZTEDYKCRG5OS547XHJ3ANAEYL3ENOR7UXAD4RSJFPTKBF5HEVIG7X67ATU
submitOrderParam.fp: 886383f37a1ca76589c8399bace2db90
riskControl: D0E404CB705B97328D0307C85B6551CBE5C4790157927E52E10D60E607B92DAD
submitOrderParam.jxj: 1
submitOrderParam.trackId: c0208ddd7c8ae4d311fbae52db6b39ae';

$a = '{"honorFreightInsureView":{"resultFlag":false,"resultCode":0,"venderHonorFreightMap":{"676426":{"honorFee":0.00,"canCheckFlag":false,"codReason":false,"venderId":676426,"checkedFlag":false}},"message":null},"newVersionDjdCalendar":null,"suportShipType":0,"promiseDjdBzd":{"showBigShipText":"<span class=\'mode-label ftx-03\'>标&nbsp;&nbsp;准&nbsp;&nbsp;达：</span><div class=\'mode-infor\'>预计&nbsp;2月29日[今天]&nbsp;送达</div>","bigItemCodDates":[],"shipAndInstall":0,"days":[],"promiseDate":null,"promiseTimeRange":null,"promiseSendPay":null,"batchId":0,"selected":false,"support":false,"cjshFlag":false,"promiseTime":{},"timeRangeTitle":[],"date_x":null,"date_y":null,"calendarV2":null,"newVersionCalendar":null,"type":0,"offset":0},"promiseZxjJzd":{"supportInstall":false,"days":[],"promiseDate":null,"promiseTimeRange":null,"promiseSendPay":null,"batchId":0,"selected":false,"support":false,"cjshFlag":false,"promiseTime":{},"timeRangeTitle":[],"show311Text":null,"tipMsg":null,"date_x":null,"date_y":null,"forcedChoice":false,"guiderJzdNight":false,"dateStr":null,"promiseMsg":null,"installDateViewList":null,"selectedInstallOffset":0,"calendarTagText":null,"defaultTagType":null,"supportCombine":false,"hasCombineCalendar":false,"calendarV2":null,"newVersionCalendar":null,"purchaseFlag":false,"type":0},"installDates":null,"installJzdOffset":0,"installJzdDates":null,"onlyHasLocNew":"","hasLocNew":"","allWmFreightWeight":"","overWmFreightWeight":"","usedPickView":{"isFirstAccess":0,"distance":0.0,"areaName":null,"paymentId":0,"selected":false,"consigneeId":0,"selfPickFlag":0,"selfPickMobile":null,"selfPickPhone":null,"selfpickSiteAvailable":false,"selfpickCounterAvailable":false,"used":false,"pickId":0,"pickName":null,"mapUrl":null,"branchId":0,"canSelected":false,"siteType":0,"helpMessage":null,"cabinetAvailable":true,"limitKeyword":0,"specialRemark":null,"addressSupported":0,"isCod":0,"consigneeName":null,"address":null,"name":null,"message":null},"nearestPickView":{"isFirstAccess":0,"distance":0.0,"areaName":null,"paymentId":0,"selected":false,"consigneeId":0,"selfPickFlag":0,"selfPickMobile":null,"selfPickPhone":null,"selfpickSiteAvailable":false,"selfpickCounterAvailable":false,"used":false,"pickId":0,"pickName":null,"mapUrl":null,"branchId":0,"canSelected":false,"siteType":0,"helpMessage":null,"cabinetAvailable":true,"limitKeyword":0,"specialRemark":null,"addressSupported":0,"isCod":0,"consigneeName":null,"address":null,"name":null,"message":null},"promiseDjdJsd":{"installDate":0,"supportSpeedArrive":false,"businessTime":null,"supportInstall":false,"resultMsg":null,"codDate":null,"sendPay":null,"speedMark":null,"resultCode":0,"selected":false,"installDateList":null,"carriageMoney":null,"txtTag":null,"txtMsg":null,"speedHour":null},"installJsdDates":null,"installJsdOffset":0,"carDeliverJzd":{"supportInstall":false,"days":[],"promiseDate":null,"promiseTimeRange":null,"promiseSendPay":null,"batchId":0,"selected":false,"support":false,"cjshFlag":false,"promiseTime":{},"timeRangeTitle":[],"show311Text":null,"tipMsg":null,"date_x":null,"date_y":null,"forcedChoice":false,"guiderJzdNight":false,"dateStr":null,"promiseMsg":null,"installDateViewList":null,"selectedInstallOffset":0,"calendarTagText":null,"defaultTagType":null,"supportCombine":false,"hasCombineCalendar":false,"calendarV2":null,"newVersionCalendar":null,"purchaseFlag":false,"type":0},"extraOrderInfo":{"addedService":[]},"allSxFreightWeight":"","overSxFreightWeight":"","allFreightWeight":"","overFreightWeight":"","selfPick":{"pickShowStatus":0,"pickShipSelected":false,"selRegionId":null,"pickDateHtml":"\t<div class=\"date-box\">\r\n\t\t<div class=\"date-list\">\r\n\t\t\t<ul>\r\n\t\t\t  \t\t\t</ul>\r\n\t\t</div>\r\n\t\t<div class=\"ftx-03 mt10\">\r\n\t\t\t\n        \n\t温馨提示：<br>\n\t1、您选择的时间可能会因库存不足等因素导致订单延迟，请您谅解！<br>\n\t2、我们会在您选定提货日期的前一天处理您的订单，在此之前您的订单处于暂停状态。\n\t\n    \r\n\t\r\n\t\t</div>\r\n\t\t<div class=\"op-btns mt20 ac\">\r\n\t\t\t<a href=\"#none\" onclick=\"doSavePickShipDate(\'\')\" class=\"btn-9\">保存</a>\r\n\t\t\t<a href=\"javascript:jQuery.closeDialog();\"  class=\"btn-9 ml10\">取消</a>\r\n\t\t</div>\r\n\t</div>\r\n\r\n<script type=\"text/javascript\">\r\n        //点击切换自提点配送时间\r\n        function doSwithPickShipDate(venderId,thisElement){\r\n\t\t\t $(\'.li_pick_shipment\').removeClass().addClass(\"li_pick_shipment\");\r\n            $(thisElement).removeClass().addClass(\"li_pick_shipment selected\");\r\n        }\r\n        \r\n        //保存自提点配送时间\r\n        function doSavePickShipDate(venderId){\r\n           $(\"#selfpick_date\").html(\'<span class=\"ftx-03\">配送时间：</span>\' + $(\'.li_pick_shipment.selected\').attr(\"picksite_date\") + \" \" + $(\'.li_pick_shipment.selected\').attr(\"picksite_weekDay\"));\r\n           $(\"#saveParam_pickDate\").val($(\'.li_pick_shipment.selected\').attr(\"date\"));\r\n           $(\"#beforePickDate\").val($(\'.li_pick_shipment.selected\').attr(\"date\"));\r\n\t\t   doSavePayAndShipmentInfo(\"jd_picksite_time\");\r\n           jQuery.closeDialog();\r\n        }\r\n</script>","pickShipmentView":"<!-- 选择自提点 -->\r\n\r\n<div class=\"form picksite-box\">\r\n\t<div class=\"item\">\r\n\t\t<span class=\"label\">选择区域：</span>\r\n\t\t<div class=\"fl\">\r\n\t\t\t<select name=\"pickRegion\" id=\"pickRegion_select\" class=\"selt pickRegion_select\" onchange=\"doEditPickReigon(this)\">\r\n\t\t\t\t\t\t   <option value=\"-1\">全部区域</option>\r\n\t\t\t\t\t\t</select>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"item\">\r\n\t\t<span class=\"label\">选择自提点：</span>\r\n\t\t<div class=\"fl\">\r\n\t\t\t<div class=\"pick-sites pick-sites-more\"  id=\"pick-sites\">\r\n\t\t\t\t<!--循环取出自提点信息开始-->\r\n\t\t\t\t\t\t\t\t\t\t\t\t<!--循环取出自提点信息结束-->\r\n\t\t\t</div>\r\n\t\t\t<div class=\"pick-more\" >\r\n\t\t\t\t<span  class=\"selfpick_more_link open ftx05 hide\"  style=\"cursor:pointer;\" onclick=\"open_MorePicksite(this)\">展开更多<b></b></span>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"item\">\r\n\t\t<span class=\"label\">&nbsp;</span>\r\n\t\t<div class=\"fl\">\r\n\t\t\t<div class=\"op-btns\">\r\n\t\t\t\t<a class=\"btn-9\" onclick=\"doSaveDialogPickSite()\">保存自提点</a>\r\n\t\t\t\t<a class=\"btn-9 ml10\" href=\"javascript:jQuery.closeDialog();\">取消</a>\r\n\t\t\t</div> \r\n\t\t\t<div class=\"ftx-03 mt10\">温馨提示：</div>\r\n\t\t\t<div class=\"ftx-03\">1、自提时付款，支持现金、POS刷卡、支票支付 <a class=\"ftx-05\" href=\"http://help.jd.com/user/issue/100-181.html\" target=\"_blank\">查看自提流程</a></div>\r\n            <div class=\"ftx-03\"><span class=\"ftx-04\">2、京东将根据您的收货地址显示其范围内的自提点，请确保您的收货地址正确填写。 </span></div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n<script type=\"text/javascript\">\r\n   //选择自提点\r\n   function doSelectPicksite(thisElement){\r\n      if($(thisElement).parent().hasClass(\"site-item-disabled\")){\r\n         //alert(\"您所选取的自提点不可用\");\r\n         return;\r\n      }\r\n      $(\"#selfpick_siteDiv .site-item\").each(function(index,item){\r\n\t       if($(this).hasClass(\"site-item-selected\")){\r\n\t           $(this).removeClass().addClass(\"site-item\");\r\n\t       }\r\n\t  });\r\n\t  if($(thisElement).parent().hasClass(\"site-item-selected\")==false){\r\n\t      $(thisElement).parent().removeClass().addClass(\"site-item site-item-selected\");\r\n\t  }\r\n   }\r\n   function doClosePickSite(){\r\n   \t   $(\".site-item\").each(function(index,item){\r\n\t       if($(this).hasClass(\"site-item-selected\")){\r\n\t           $(this).removeClass().addClass(\"site-item\");\r\n\t       }\r\n\t  });\r\n\t  javascript:jQuery.closeDialog();\r\n   }\r\n</script>","pickDate":null,"recommended":false,"pickSiteNum":0,"showBanDateTip":null,"simplePickDate":null,"weekDay":null,"selectedPickView":{"isFirstAccess":0,"distance":0.0,"areaName":null,"paymentId":0,"selected":false,"consigneeId":0,"selfPickFlag":0,"selfPickMobile":null,"selfPickPhone":null,"selfpickSiteAvailable":false,"selfpickCounterAvailable":false,"used":false,"pickId":0,"pickName":null,"mapUrl":null,"branchId":0,"canSelected":false,"siteType":0,"helpMessage":null,"cabinetAvailable":true,"limitKeyword":0,"specialRemark":null,"addressSupported":0,"isCod":0,"consigneeName":null,"address":null,"name":null,"message":null},"noSupportSelfPickSkuList":null,"pickName":null},"promiseDjdJzd":{"showBigShipText":"<span class=\'mode-label ftx-03\'>标&nbsp;&nbsp;准&nbsp;&nbsp;达：</span><div class=\'mode-infor\'>预计&nbsp;2月29日[今天]&nbsp;送达</div>","bigItemCodDates":[],"shipAndInstall":0,"days":[],"promiseDate":null,"promiseTimeRange":null,"promiseSendPay":null,"batchId":0,"selected":false,"support":false,"cjshFlag":false,"promiseTime":{},"timeRangeTitle":[],"date_x":null,"date_y":null,"calendarV2":null,"newVersionCalendar":null,"type":0,"offset":0},"combine":false,"calendarVersion":1,"page":null,"promise311":{"supportInstall":false,"days":[],"promiseDate":null,"promiseTimeRange":null,"promiseSendPay":null,"batchId":0,"selected":false,"support":false,"cjshFlag":false,"promiseTime":{},"timeRangeTitle":[],"show311Text":null,"tipMsg":null,"date_x":null,"date_y":null,"forcedChoice":false,"guiderJzdNight":false,"dateStr":null,"promiseMsg":null,"installDateViewList":null,"selectedInstallOffset":0,"calendarTagText":null,"defaultTagType":null,"supportCombine":false,"hasCombineCalendar":false,"calendarV2":null,"newVersionCalendar":null,"purchaseFlag":false,"type":0},"promise411":{"dataFlag":false,"grayFlag":false,"grayMsg":null,"timeRange":null,"siteName":null,"productionEndTime":null,"cutOrderTime":null,"delieveredTime":null,"store2Site":null,"finalDelieveredTime":null,"delieverDistance":null,"sendPay":null,"selected":false,"support":false,"carriageMoney":null,"siteId":0,"promiseMsg":null},"success":true,"orderPrice":{"usedBalance":0.00,"checked":false,"detail":{},"canReplacement":false,"cartAddedServiceTotalFee":0,"serviceTotalFee":0.00,"buyerFreightInsurance":0.00,"venderFreight":{"0":0},"couponDiscount":0.00,"freeFreight":0.00,"giftCardDiscount":0.00,"hyjDiscount":0.00,"replacementDiscount":0.00,"periodFee":null,"selectRedPacket":false,"couponNum":0,"freightCouponNum":0,"giftCardNum":0,"presaleRealDingjin":0,"presaleDingJinFactPrice":null,"presaleRealFreight":0,"presaleRealWeikuan":0,"crossRegionalFee":null,"gstTaxAmount":0.00,"overseaOriginalFreight":0,"overseaOriginalBookFreight":0,"overseaPromotionFreight":0,"overseaPromotionBookFreight":0,"overseaPromotionTotalFreight":0,"overseaOriginalTotalFreight":0,"overseaBookFreight":0,"overseaNoBookFreight":0,"totalParallelDiscount":"0.00","remoteSkuNum":0,"consignmentCardDiscount":0.00,"consignmentCardNum":0,"jzdAmount":"京准达","jsdAmount":"极速达（￥99.00）","djzdAmount":"京准达","freight":0.00,"leaveBalance":0.00,"sxXuZhongFreight":null,"sxBaseFreight":null,"promotionPrice":2399.00,"cashBack":100.00,"payPrice":2299.00,"usedJdBeanDiscout":0,"cancelReplacement":false,"venderfreightSkuViews":{"676426":[{"book":false,"sxType":0,"supportInstall":false,"bigItem":false,"factoryShip":false,"yanbao":false,"num":1,"remoteSkuFreight":0,"venderId":676426,"imgUrl":"jfs/t1/91339/20/11462/191293/5e3632c9Eb86da2b7/b88597846f4c67d7.jpg","name":"海尔滚筒洗衣机 9/10公斤洗烘一体机烘干干衣机 全自动变频烘干 空气洗桶自洁 即洗即穿 节能静音 9公斤白色  智能物联","id":12834877251}]},"venderRemoteFreight":{},"detailJson":null,"venderFreightJson":null,"sopJzdFreight":{},"redPacketDiscount":0.00,"redPacketBalance":null,"skuNum":1},"totalFreightWeightShow":"","allXuZhongWeightSamSXShow":null,"overXuZhongWeightSamSX":"","allXuZhongWeightSamGenShow":"","overXuZhongWeightSamGen":"","allXuZhongWeightSCFShow":"","overXuZhongWeightSCF":"","venderId":0,"packagingServices":{"select":false,"support":false,"packageCharge":null,"venderPackagingServicesView":null},"cartJson":"[{\"id\":12834877251,\"num\":1,\"shopId\":676426,\"cid\":880,\"gift\":false},{\"id\":12358462423,\"num\":1,\"shopId\":676426,\"cid\":870,\"gift\":true},{\"id\":12422442713,\"num\":1,\"shopId\":676426,\"cid\":880,\"gift\":true},{\"id\":16322037842,\"num\":1,\"shopId\":676426,\"cid\":880,\"gift\":true}]","isSelfPickShutDown":1,"selfPickOptimize":1,"noAvailableSku":{},"restDay":"0","saveMoneyType":"1","saveMoney":"0","existUnSupportSkus":"0","unSupportSelfPickSkuList":null,"copyContent":null,"pageIndex":0,"pageSize":0,"promiseSopViewList":[{"newVersionDjdCalendar":null,"showSopText":null,"showSopJdText":null,"supportBigShipmentJzd":false,"pickDateList":null,"sopJdShipment":false,"sopOtherShipment":true,"shipType":0,"sopVenderPickState":false,"sopVenderPickShipment":false,"supportGSDShipForPop":0,"jdPromiseType":0,"jdDjdPromiseType":0,"venderSelfDeliveryStoreView":{"businessHours":null,"recentlyMark":0,"stockStatus":0,"distance":null,"storeAddress":null,"storeMark":0,"venderId":-1,"storeId":null,"longitude":0.0,"latitude":0.0,"warehouseId":0,"name":null},"sopGsdShipment":false,"sopGsdSupport":false,"promiseGsdView":null,"sopPromise311View":null,"supportSopPromise311":false,"bigShipmentJzdDateView":null,"sopBigShipmentDateView":null,"days":[],"pickDate":"","promiseDate":null,"promiseTimeRange":null,"promiseSendPay":null,"batchId":0,"selected":false,"support":true,"venderId":676426,"cjshFlag":false,"timeRangeTitle":[],"tipMsg":null,"date_x":null,"date_y":null,"newVersionCalendar":null,"type":0}],"supportHonorFreight":false,"selectHonorFreight":false,"gsd":{"sendpay":null,"grayFlag":false,"timeRange":null,"siteName":null,"productionEndTime":null,"cutOrderTime":null,"delieveredTime":null,"store2Site":null,"finalDelieveredTime":null,"delieverDistance":null,"support":false,"hasCalendar":false,"shipText":null,"immediately":false,"days":[],"promiseDate":null,"promiseTimeRange":null,"batchId":0,"selectedItem":-1,"selected":false,"carriageMoney":null,"siteId":0,"timeRangeTitle":[],"date_x":"","date_y":"","forcedChoice":false,"promiseMsg":null,"calendarTagText":null,"defaultTagType":null,"newVersionCalendar":null},"freightInsureView":{"venderInsuranceList":[{"venderName":"海尔腾妙专卖店","insuranceFee":0.00,"showFlag":true,"insuranceType":2,"claimFee":0,"insuranceCopy":"7天内退货，15天内换货，可享1次运费赔付到小金库","venderId":676426,"checkedFlag":true,"type":1}]},"cjshFlag":false,"resetShipTime":{"shipType":0,"reset":false,"shipName":null},"newVersionCalendar":null,"installOffset":0}';

$b = '{
	"allSxFreightWeight": "",
	"overSxFreightWeight": "",
	"allFreightWeight": "0.360kg",
	"overFreightWeight": "",
	"selfPick": {
		"pickDateHtml": "\t<div class=\"date-box\">\r\n\t\t<div class=\"date-list\">\r\n\t\t\t<ul>\r\n\t\t\t  \t\t\t</ul>\r\n\t\t</div>\r\n\t\t<div class=\"ftx-03 mt10\">\r\n\t\t\t\n        \n\t温馨提示：<br>\n\t1、您选择的时间可能会因库存不足等因素导致订单延迟，请您谅解！<br>\n\t2、我们会在您选定提货日期的前一天处理您的订单，在此之前您的订单处于暂停状态。\n\t\n    \r\n\t\r\n\t\t</div>\r\n\t\t<div class=\"op-btns mt20 ac\">\r\n\t\t\t<a href=\"#none\" onclick=\"doSavePickShipDate(\'\')\" class=\"btn-9\">保存</a>\r\n\t\t\t<a href=\"javascript:jQuery.closeDialog();\"  class=\"btn-9 ml10\">取消</a>\r\n\t\t</div>\r\n\t</div>\r\n\r\n<script type=\"text/javascript\">\r\n        //点击切换自提点配送时间\r\n        function doSwithPickShipDate(venderId,thisElement){\r\n\t\t\t $(\'.li_pick_shipment\').removeClass().addClass(\"li_pick_shipment\");\r\n            $(thisElement).removeClass().addClass(\"li_pick_shipment selected\");\r\n        }\r\n        \r\n        //保存自提点配送时间\r\n        function doSavePickShipDate(venderId){\r\n           $(\"#selfpick_date\").html(\'<span class=\"ftx-03\">配送时间：</span>\' + $(\'.li_pick_shipment.selected\').attr(\"picksite_date\") + \" \" + $(\'.li_pick_shipment.selected\').attr(\"picksite_weekDay\"));\r\n           $(\"#saveParam_pickDate\").val($(\'.li_pick_shipment.selected\').attr(\"date\"));\r\n           $(\"#beforePickDate\").val($(\'.li_pick_shipment.selected\').attr(\"date\"));\r\n\t\t   doSavePayAndShipmentInfo(\"jd_picksite_time\");\r\n           jQuery.closeDialog();\r\n        }\r\n</script>",
		"selRegionId": null,
		"pickShowStatus": 0,
		"pickShipSelected": false,
		"pickShipmentView": "<!-- 选择自提点 -->\r\n\r\n<div class=\"form picksite-box\">\r\n\t<div class=\"item\">\r\n\t\t<span class=\"label\">选择区域：</span>\r\n\t\t<div class=\"fl\">\r\n\t\t\t<select name=\"pickRegion\" id=\"pickRegion_select\" class=\"selt pickRegion_select\" onchange=\"doEditPickReigon(this)\">\r\n\t\t\t\t\t\t   <option value=\"-1\">全部区域</option>\r\n\t\t\t\t\t\t</select>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"item\">\r\n\t\t<span class=\"label\">选择自提点：</span>\r\n\t\t<div class=\"fl\">\r\n\t\t\t<div class=\"pick-sites pick-sites-more\"  id=\"pick-sites\">\r\n\t\t\t\t<!--循环取出自提点信息开始-->\r\n\t\t\t\t\t\t\t\t\t\t\t\t<!--循环取出自提点信息结束-->\r\n\t\t\t</div>\r\n\t\t\t<div class=\"pick-more\" >\r\n\t\t\t\t<span  class=\"selfpick_more_link open ftx05 hide\"  style=\"cursor:pointer;\" onclick=\"open_MorePicksite(this)\">展开更多<b></b></span>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"item\">\r\n\t\t<span class=\"label\">&nbsp;</span>\r\n\t\t<div class=\"fl\">\r\n\t\t\t<div class=\"op-btns\">\r\n\t\t\t\t<a class=\"btn-9\" onclick=\"doSaveDialogPickSite()\">保存自提点</a>\r\n\t\t\t\t<a class=\"btn-9 ml10\" href=\"javascript:jQuery.closeDialog();\">取消</a>\r\n\t\t\t</div> \r\n\t\t\t<div class=\"ftx-03 mt10\">温馨提示：</div>\r\n\t\t\t<div class=\"ftx-03\">1、自提时付款，支持现金、POS刷卡、支票支付 <a class=\"ftx-05\" href=\"http://help.jd.com/user/issue/100-181.html\" target=\"_blank\">查看自提流程</a></div>\r\n            <div class=\"ftx-03\"><span class=\"ftx-04\">2、京东将根据您的收货地址显示其范围内的自提点，请确保您的收货地址正确填写。 </span></div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n<script type=\"text/javascript\">\r\n   //选择自提点\r\n   function doSelectPicksite(thisElement){\r\n      if($(thisElement).parent().hasClass(\"site-item-disabled\")){\r\n         //alert(\"您所选取的自提点不可用\");\r\n         return;\r\n      }\r\n      $(\"#selfpick_siteDiv .site-item\").each(function(index,item){\r\n\t       if($(this).hasClass(\"site-item-selected\")){\r\n\t           $(this).removeClass().addClass(\"site-item\");\r\n\t       }\r\n\t  });\r\n\t  if($(thisElement).parent().hasClass(\"site-item-selected\")==false){\r\n\t      $(thisElement).parent().removeClass().addClass(\"site-item site-item-selected\");\r\n\t  }\r\n   }\r\n   function doClosePickSite(){\r\n   \t   $(\".site-item\").each(function(index,item){\r\n\t       if($(this).hasClass(\"site-item-selected\")){\r\n\t           $(this).removeClass().addClass(\"site-item\");\r\n\t       }\r\n\t  });\r\n\t  javascript:jQuery.closeDialog();\r\n   }\r\n</script>",
		"pickName": null,
		"selectedPickView": {
			"distance": 0.0,
			"used": false,
			"pickId": 0,
			"pickName": null,
			"mapUrl": null,
			"branchId": 0,
			"canSelected": false,
			"siteType": 0,
			"helpMessage": null,
			"cabinetAvailable": true,
			"limitKeyword": 0,
			"specialRemark": null,
			"addressSupported": 0,
			"isCod": 0,
			"consigneeName": null,
			"selfpickSiteAvailable": false,
			"selfpickCounterAvailable": false,
			"isFirstAccess": 0,
			"areaName": null,
			"paymentId": 0,
			"selected": false,
			"consigneeId": 0,
			"selfPickFlag": 0,
			"selfPickMobile": null,
			"selfPickPhone": null,
			"address": null,
			"name": null,
			"message": null
		},
		"noSupportSelfPickSkuList": null,
		"simplePickDate": null,
		"weekDay": null,
		"recommended": false,
		"pickDate": null,
		"pickSiteNum": 0,
		"showBanDateTip": null
	},
	"suportShipType": 0,
	"promiseDjdJzd": {
		"showBigShipText": "<span class=\'mode-label ftx-03\'>标&nbsp;&nbsp;准&nbsp;&nbsp;达：</span><div class=\'mode-infor\'>预计&nbsp;2月29日[今天]&nbsp;送达</div>",
		"bigItemCodDates": [],
		"shipAndInstall": 0,
		"days": [],
		"cjshFlag": false,
		"promiseDate": null,
		"promiseTimeRange": null,
		"promiseSendPay": null,
		"batchId": 0,
		"selected": false,
		"support": false,
		"promiseTime": {},
		"timeRangeTitle": [],
		"date_x": null,
		"date_y": null,
		"calendarV2": null,
		"newVersionCalendar": null,
		"type": 0,
		"offset": 0
	},
	"promiseDjdBzd": {
		"showBigShipText": "<span class=\'mode-label ftx-03\'>标&nbsp;&nbsp;准&nbsp;&nbsp;达：</span><div class=\'mode-infor\'>预计&nbsp;2月29日[今天]&nbsp;送达</div>",
		"bigItemCodDates": [],
		"shipAndInstall": 0,
		"days": [],
		"cjshFlag": false,
		"promiseDate": null,
		"promiseTimeRange": null,
		"promiseSendPay": null,
		"batchId": 0,
		"selected": false,
		"support": false,
		"promiseTime": {},
		"timeRangeTitle": [],
		"date_x": null,
		"date_y": null,
		"calendarV2": null,
		"newVersionCalendar": null,
		"type": 0,
		"offset": 0
	},
	"promiseZxjJzd": {
		"supportInstall": false,
		"days": [],
		"cjshFlag": false,
		"promiseDate": null,
		"promiseTimeRange": null,
		"promiseSendPay": null,
		"batchId": 0,
		"selected": false,
		"support": false,
		"promiseTime": {},
		"timeRangeTitle": [],
		"show311Text": null,
		"tipMsg": null,
		"date_x": null,
		"date_y": null,
		"forcedChoice": false,
		"guiderJzdNight": false,
		"dateStr": null,
		"promiseMsg": null,
		"installDateViewList": null,
		"selectedInstallOffset": 0,
		"calendarTagText": null,
		"defaultTagType": null,
		"supportCombine": false,
		"hasCombineCalendar": false,
		"calendarV2": null,
		"newVersionCalendar": null,
		"purchaseFlag": false,
		"type": 0
	},
	"installDates": null,
	"installJzdOffset": 0,
	"installJzdDates": null,
	"onlyHasLocNew": "",
	"hasLocNew": "",
	"allWmFreightWeight": "",
	"overWmFreightWeight": "",
	"usedPickView": {
		"distance": 0.2,
		"used": false,
		"pickId": 686996,
		"pickName": "京东便民站-新大街京东便利店",
		"mapUrl": null,
		"branchId": 0,
		"canSelected": false,
		"siteType": 0,
		"helpMessage": null,
		"cabinetAvailable": true,
		"limitKeyword": 0,
		"specialRemark": null,
		"addressSupported": 0,
		"isCod": 0,
		"consigneeName": null,
		"selfpickSiteAvailable": true,
		"selfpickCounterAvailable": true,
		"isFirstAccess": 0,
		"areaName": null,
		"paymentId": 0,
		"selected": false,
		"consigneeId": 0,
		"selfPickFlag": 0,
		"selfPickMobile": "188****1654",
		"selfPickPhone": null,
		"address": "广东省广州市天河区上社口岗新大街12巷5号",
		"name": "卢文钊",
		"message": null
	},
	"nearestPickView": {
		"distance": 0.2,
		"used": false,
		"pickId": 482949,
		"pickName": "京东便民站-胡岗8仔商店",
		"mapUrl": null,
		"branchId": 0,
		"canSelected": false,
		"siteType": 0,
		"helpMessage": null,
		"cabinetAvailable": true,
		"limitKeyword": 0,
		"specialRemark": null,
		"addressSupported": 0,
		"isCod": 0,
		"consigneeName": null,
		"selfpickSiteAvailable": true,
		"selfpickCounterAvailable": true,
		"isFirstAccess": 0,
		"areaName": null,
		"paymentId": 0,
		"selected": false,
		"consigneeId": 0,
		"selfPickFlag": 0,
		"selfPickMobile": "188****1654",
		"selfPickPhone": null,
		"address": "广东省广州市天河区上社胡岗新村六巷2号首层\n",
		"name": "卢文钊",
		"message": null
	},
	"promiseDjdJsd": {
		"installDate": 0,
		"supportSpeedArrive": false,
		"businessTime": null,
		"supportInstall": false,
		"codDate": null,
		"sendPay": null,
		"speedMark": null,
		"resultCode": 0,
		"selected": false,
		"installDateList": null,
		"carriageMoney": null,
		"txtTag": null,
		"txtMsg": null,
		"speedHour": null,
		"resultMsg": null
	},
	"installJsdDates": null,
	"installJsdOffset": 0,
	"carDeliverJzd": {
		"supportInstall": false,
		"days": [],
		"cjshFlag": false,
		"promiseDate": null,
		"promiseTimeRange": null,
		"promiseSendPay": null,
		"batchId": 0,
		"selected": false,
		"support": false,
		"promiseTime": {},
		"timeRangeTitle": [],
		"show311Text": null,
		"tipMsg": null,
		"date_x": null,
		"date_y": null,
		"forcedChoice": false,
		"guiderJzdNight": false,
		"dateStr": null,
		"promiseMsg": null,
		"installDateViewList": null,
		"selectedInstallOffset": 0,
		"calendarTagText": null,
		"defaultTagType": null,
		"supportCombine": false,
		"hasCombineCalendar": false,
		"calendarV2": null,
		"newVersionCalendar": null,
		"purchaseFlag": false,
		"type": 0
	},
	"extraOrderInfo": {
		"addedService": []
	},
	"honorFreightInsureView": {
		"resultFlag": false,
		"resultCode": 0,
		"venderHonorFreightMap": {
			"0": {
				"honorFee": 49.00,
				"codReason": false,
				"canCheckFlag": true,
				"venderId": 0,
				"checkedFlag": false
			}
		},
		"message": null
	},
	"newVersionDjdCalendar": null,
	"page": null,
	"gsd": {
		"siteName": null,
		"sendpay": null,
		"grayFlag": false,
		"timeRange": null,
		"productionEndTime": null,
		"cutOrderTime": null,
		"delieveredTime": null,
		"store2Site": null,
		"finalDelieveredTime": null,
		"delieverDistance": null,
		"support": false,
		"hasCalendar": false,
		"shipText": null,
		"immediately": false,
		"days": [],
		"selectedItem": -1,
		"promiseDate": null,
		"promiseTimeRange": null,
		"batchId": 0,
		"selected": false,
		"carriageMoney": null,
		"siteId": 0,
		"timeRangeTitle": [],
		"date_x": "",
		"date_y": "",
		"forcedChoice": false,
		"promiseMsg": null,
		"calendarTagText": null,
		"defaultTagType": null,
		"newVersionCalendar": null
	},
	"cjshFlag": false,
	"freightInsureView": {
		"venderInsuranceList": [{
			"venderName": "",
			"insuranceFee": 0.70,
			"showFlag": true,
			"insuranceType": 0,
			"claimFee": 0.00,
			"insuranceCopy": "",
			"venderId": 0,
			"checkedFlag": false,
			"type": 2
		}]
	},
	"resetShipTime": {
		"shipType": 3,
		"reset": true,
		"shipName": "<span class=\"ftx-03\">配送时间：</span>工作日、双休日与节假日均可送货"
	},
	"calendarVersion": 1,
	"combine": false,
	"promise311": {
		"supportInstall": false,
		"days": [],
		"cjshFlag": false,
		"promiseDate": null,
		"promiseTimeRange": null,
		"promiseSendPay": null,
		"batchId": 0,
		"selected": false,
		"support": false,
		"promiseTime": {},
		"timeRangeTitle": [],
		"show311Text": null,
		"tipMsg": null,
		"date_x": null,
		"date_y": null,
		"forcedChoice": false,
		"guiderJzdNight": false,
		"dateStr": null,
		"promiseMsg": null,
		"installDateViewList": null,
		"selectedInstallOffset": 0,
		"calendarTagText": null,
		"defaultTagType": null,
		"supportCombine": false,
		"hasCombineCalendar": false,
		"calendarV2": null,
		"newVersionCalendar": null,
		"purchaseFlag": false,
		"type": 0
	},
	"promise411": {
		"dataFlag": false,
		"siteName": null,
		"grayFlag": false,
		"grayMsg": null,
		"timeRange": null,
		"productionEndTime": null,
		"cutOrderTime": null,
		"delieveredTime": null,
		"store2Site": null,
		"finalDelieveredTime": null,
		"delieverDistance": null,
		"sendPay": null,
		"selected": false,
		"support": false,
		"carriageMoney": null,
		"siteId": 0,
		"promiseMsg": null
	},
	"success": true,
	"orderPrice": {
		"usedBalance": 0.00,
		"checked": false,
		"skuNum": 3,
		"sxXuZhongFreight": null,
		"sxBaseFreight": null,
		"promotionPrice": 532.50,
		"cashBack": 0.00,
		"payPrice": 532.50,
		"usedJdBeanDiscout": 0,
		"cancelReplacement": false,
		"venderfreightSkuViews": {
			"0": [{
				"book": false,
				"sxType": 0,
				"supportInstall": false,
				"bigItem": false,
				"factoryShip": false,
				"yanbao": false,
				"imgUrl": "jfs/t1/105520/7/9331/178668/5e0d711dEc913f5bb/259fb24eac938cb7.jpg",
				"num": 1,
				"remoteSkuFreight": 0,
				"venderId": 0,
				"name": "北通(Betop)蝙蝠D2F有线游戏手柄 PC360电脑Steam安卓电视荒野大镖客2刺客信条怪物猎人世界实况足球 黑",
				"id": 1755629
			}, {
				"book": false,
				"sxType": 0,
				"supportInstall": false,
				"bigItem": false,
				"factoryShip": false,
				"yanbao": false,
				"imgUrl": "jfs/t1/7081/32/3784/126135/5bd87a2aE4c0853ed/b0f11ed674be3df4.jpg",
				"num": 1,
				"remoteSkuFreight": 0,
				"venderId": 0,
				"name": "东芝（TOSHIBA）16GB USB2.0 U盘 U202经典隼系列 电脑 车载浅蓝色U盘",
				"id": 877117
			}, {
				"book": false,
				"sxType": 0,
				"supportInstall": false,
				"bigItem": false,
				"factoryShip": false,
				"yanbao": false,
				"imgUrl": "jfs/t18418/49/544997159/709724/14345981/5a961b7fN8099553c.jpg",
				"num": 1,
				"remoteSkuFreight": 0,
				"venderId": 0,
				"name": "英特尔（Intel）256GB SSD固态硬盘 M.2接口(NVMe协议) 760P系列 2280板型",
				"id": 6275020
			}]
		},
		"venderRemoteFreight": {},
		"venderFreightJson": null,
		"detailJson": null,
		"sopJzdFreight": {},
		"redPacketDiscount": 0.00,
		"redPacketBalance": null,
		"detail": {
			"10": 0
		},
		"canReplacement": false,
		"cartAddedServiceTotalFee": 0,
		"serviceTotalFee": 0.00,
		"buyerFreightInsurance": 0.00,
		"venderFreight": {
			"0": 0
		},
		"couponDiscount": 0.00,
		"freeFreight": 0.00,
		"giftCardDiscount": 0.00,
		"hyjDiscount": 0.00,
		"replacementDiscount": 0.00,
		"periodFee": null,
		"selectRedPacket": false,
		"couponNum": 0,
		"freightCouponNum": 0,
		"giftCardNum": 0,
		"presaleRealDingjin": 0,
		"presaleDingJinFactPrice": null,
		"presaleRealFreight": 0,
		"presaleRealWeikuan": 0,
		"crossRegionalFee": null,
		"gstTaxAmount": 0.00,
		"overseaOriginalFreight": 0,
		"overseaOriginalBookFreight": 0,
		"overseaPromotionFreight": 0,
		"overseaPromotionBookFreight": 0,
		"overseaPromotionTotalFreight": 0,
		"overseaOriginalTotalFreight": 0,
		"overseaBookFreight": 0,
		"overseaNoBookFreight": 0,
		"totalParallelDiscount": "0.00",
		"remoteSkuNum": 0,
		"consignmentCardDiscount": 0.00,
		"consignmentCardNum": 0,
		"jzdAmount": "京准达",
		"jsdAmount": "极速达（￥99）",
		"djzdAmount": "京准达",
		"freight": 0.00,
		"leaveBalance": 0.00
	},
	"totalFreightWeightShow": "0.360",
	"allXuZhongWeightSamSXShow": null,
	"overXuZhongWeightSamSX": "",
	"allXuZhongWeightSamGenShow": "",
	"overXuZhongWeightSamGen": "",
	"allXuZhongWeightSCFShow": "",
	"overXuZhongWeightSCF": "",
	"venderId": 0,
	"packagingServices": {
		"venderPackagingServicesView": null,
		"select": false,
		"support": false,
		"packageCharge": null
	},
	"cartJson": "[{\"id\":6275020,\"num\":1,\"shopId\":0,\"cid\":11303,\"gift\":false},{\"id\":1755629,\"num\":1,\"shopId\":0,\"cid\":12803,\"gift\":false},{\"id\":877117,\"num\":1,\"shopId\":0,\"cid\":694,\"gift\":false}]",
	"isSelfPickShutDown": 1,
	"selfPickOptimize": 1,
	"noAvailableSku": {},
	"restDay": "0",
	"saveMoneyType": "1",
	"saveMoney": "0",
	"existUnSupportSkus": "0",
	"unSupportSelfPickSkuList": null,
	"copyContent": null,
	"pageIndex": 0,
	"pageSize": 0,
	"promiseSopViewList": [],
	"supportHonorFreight": true,
	"selectHonorFreight": false,
	"newVersionCalendar": null,
	"installOffset": 0
}';

/**
 *
 * beforePickSiteId 自提点
 *
 *onlinepaytype  支付方式   payid = 4  onlinepaytype = 0
 *
 * doSelectSelfPickSiteOptimize() 参数2判断是否上次用自提点
 *
 *
 *
 *
 */
